// Package harness produces artifacts consumable by Harness STO (Security Test Orchestration).
//
//   - STO ingests SARIF natively. We expose `WriteSTOSarif` for that path.
//   - For pipelines we also generate a `harness-step.yaml` snippet that calls
//     llmscan with the right flags and uploads the SARIF report.
package harness

import (
	"fmt"
	"io"

	"github.com/andrewaeva/llmscan/internal/report"
	"github.com/andrewaeva/llmscan/internal/types"
)

// WriteSTOSarif emits the SARIF report Harness STO can ingest.
// It is a thin alias kept here so users see the integration in one place.
func WriteSTOSarif(w io.Writer, r types.Report) error {
	return report.WriteSARIF(w, r)
}

// StepOptions configures the Harness pipeline snippet.
type StepOptions struct {
	Identifier string // e.g. "llmscan_sast"
	Name       string // e.g. "LLM SAST"
	Image      string // docker image hosting llmscan binary
	TargetPath string // path inside the workspace
	ConfigPath string // optional, llmscan.yaml
	FailOn     string // critical|high|medium|low
}

// WriteStepYAML writes a Harness STO step template snippet ready to paste into a pipeline.
// It uses the "custom_ingest" SAST step variant so STO can ingest llmscan's SARIF.
func WriteStepYAML(w io.Writer, opt StepOptions) error {
	if opt.Identifier == "" {
		opt.Identifier = "llmscan_sast"
	}
	if opt.Name == "" {
		opt.Name = "LLM SAST"
	}
	if opt.Image == "" {
		opt.Image = "ghcr.io/andrewaeva/llmscan:latest"
	}
	if opt.TargetPath == "" {
		opt.TargetPath = "."
	}
	tmpl := `# Generated by llmscan -- paste into a Harness CI/STO pipeline stage.
- step:
    type: Security
    name: %q
    identifier: %s
    spec:
      privileged: false
      image: %s
      settings:
        policy_type: orchestratedScan
        scan_type: repository
        product_name: llmscan
        product_config_name: default
        target_type: repository
        target_name: <+pipeline.identifier>
        target_variant: <+codebase.branch>
        target_workspace: %s
      shell: Sh
      command: |
        llmscan scan %s%s --format sarif -o /harness/llmscan.sarif --fail-on %s
        cat /harness/llmscan.sarif
      reports:
        type: SARIF
        spec:
          paths:
            - /harness/llmscan.sarif
`
	cfgArg := ""
	if opt.ConfigPath != "" {
		cfgArg = " -c " + opt.ConfigPath
	}
	failOn := opt.FailOn
	if failOn == "" {
		failOn = "high"
	}
	_, err := fmt.Fprintf(w, tmpl,
		opt.Name, opt.Identifier, opt.Image, opt.TargetPath,
		opt.TargetPath, cfgArg, failOn)
	return err
}
